Pipfile, Pipfile.lock, solgate/utils/io.py, tests/__init__.py, tests/utils/__init__.py, tests/utils/io_test.py
#1 
Starting a test suite for the package. Starting with the key formatter.
=> Add testsuite for key formatter

solgate/utils/io.py
Simple change removing unnecessary dead code from key formatter
=> Remove dead code from key formatter

Pipfile, Pipfile.lock, solgate/__init__.py, solgate/cli.py, solgate/transfer.py, solgate/utils/__init__.py, solgate/utils/io.py, tests/conftest.py, tests/fixtures/different_clients.ini, tests/fixtures/same_client.ini, tests/fixtures/same_flags.ini, tests/fixtures/without_source_formatter.ini, tests/transfer_test.py, tests/utils/io_test.py
Implements #1 for whole transfer process
Refactor the transfer logic to be able to transfer multiple files to multiple locations at once. CLI support for both variants in a single command.
With full test coverage with mocked S3.
=> Transfer multiple file to multiple locations at once

solgate/__init__.py, solgate/cli.py, solgate/lookup.py, solgate/utils/io.py, solgate/utils/s3.py, tests/fixtures/multiple_sources.ini, tests/lookup_test.py, tests/utils/io_test.py, tests/utils/s3_test.py
Resolves #1 
Reach intended 100% code coverage and squash some bugs along the way.
=> Additional test suites for Lookup, S3 and IO

solgate/cli.py, tests/cli_test.py
…
The only test suite missing and I hit a bug in the 'cli' code right away using the quay images... Who would have guessed. So here it is. Let's cover the last remaining bits with tests...
=> Add CLI test suite

.aicoe-ci.yaml
Related-To: https://github.com/AICoE/aicoe-ci/issues/41
aicoe-ci configuration file enables aicoe-ci to fetch required configurations.
enable py3.8 based pull request check
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
=> enable py3.8 based pull request check

.aicoe-ci.yaml
…
Makes AICoE-CI deploy to `latest` tag on release as well.
=> Use custom 'latest' tag as an additional push target

solgate/report.py, tests/report_test.py
n/a
Fixes deserialization of `{{workflow.failures}}` string passed from Argo. Argo parses a string that is usable in scripts - escaped and starting/ending with a quote.. This is not usable when failures are passed via environment variable... We need some preprocessing on the data - like `decode().encode('unicode_escape')[1:-1]` etc..
=> Fix deserialization of Argo failures

manifests/base/kustomization.yaml, manifests/base/sa-default-view.yaml, manifests/base/sensor.yaml, manifests/base/wftmpl.yaml
**Do not merge**
…
Use PV for intermediate storage - exchange of data between steps, and query for the Argo Server route dynamically, during the onExit handler execution.
=> Use PV for data exchange and fetch argo server role on the fly

README.md, solgate/cli.py
Resolves: #18 #11 
Expects the #53 to land soon.
=> Update documentation with example config and dev section

solgate/cli.py, solgate/lookup.py, solgate/report.py, solgate/transfer.py, solgate/utils/__init__.py, solgate/utils/email_alert_template.html, solgate/utils/email_alert_template.txt, solgate/utils/exceptions.py, solgate/utils/io.py, solgate/utils/s3.py, tests/cli_test.py, tests/lookup_test.py, tests/report_test.py, tests/transfer_test.py, tests/utils/io_test.py, tests/utils/s3_test.py
#63 
Enriches the reporting with error codes and explanations for different return states.
=> feat: Enrich reporting with error codes for different failure cases

manifests/overlays/prod/kustomization.yaml, manifests/overlays/prod/usir-stage/cronwf.yaml, manifests/overlays/prod/usir-stage/kustomization.yaml, manifests/overlays/prod/usir-stage/secret-generator.yaml, manifests/overlays/prod/usir-stage/secret.enc.yaml
SSIA
Add USIR stage pipeline for Kevin
=> feat: Add USIR stage sync pipeline

manifests/overlays/prod/tower-analytics-prod/cronwf.yaml, manifests/overlays/prod/tower-analytics-prod/kustomization.yaml, manifests/overlays/prod/tower-analytics-prod/secret-generator.yaml, manifests/overlays/prod/tower-analytics-prod/secret.enc.yaml, manifests/overlays/prod/tower-analytics-stage/cronwf.yaml, manifests/overlays/prod/tower-analytics-stage/kustomization.yaml, manifests/overlays/prod/tower-analytics-stage/secret-generator.yaml, manifests/overlays/prod/tower-analytics-stage/secret.enc.yaml
SSIA
Related to: https://github.com/aicoe-aiops/sync-pipelines-private/issues/23
Reporting to my email only, not yet to the DH alerts list.
=> feat: Add Tower Analytics stage/prod sync pipelines

manifests/overlays/prod/kustomization.yaml
=> fix: Enable tower analytics sync

solgate/cli.py, solgate/lookup.py, solgate/utils/__init__.py, solgate/utils/io.py, solgate/utils/s3.py, tests/cli_test.py, tests/lookup_test.py, tests/transfer_test.py, tests/utils/io_test.py, tests/utils/s3_test.py
Resolves: https://github.com/aicoe-aiops/sync-pipelines/issues/82
=> Make S3 remote object listing dynamic via generators

manifests/base/wftmpl.yaml, solgate/cli.py, tests/cli_test.py
=> fix: Backfill param passing from workflow

solgate/cli.py
=> fix(logging): Add logging for backfill listing

manifests/overlays/prod/kustomization.yaml, manifests/overlays/prod/rhods-usage-metrics/cronwf.yaml, manifests/overlays/prod/rhods-usage-metrics/kustomization.yaml, manifests/overlays/prod/rhods-usage-metrics/secret-generator.yaml, manifests/overlays/prod/rhods-usage-metrics/secret.enc.yaml
Adds kustomize artifacts required to create a sync pipeline between AWS and internal Ceph S3 buckets for RHODS usage metrics
=> Add sync pipeline for rhods-metrics

manifests/overlays/prod/cost-management/cronwf.yaml, manifests/overlays/prod/cost-management/kustomization.yaml, manifests/overlays/prod/cost-management/secret-generator.yaml, manifests/overlays/prod/kustomization.yaml
None
Add required objects to sync the cost management data using Solgate
=> Add sync pipeline for cost-management data

manifests/overlays/prod/cost-management/cost-management.enc.yaml
=> Add the secret config for cost management sync pipeline

solgate/cli.py, solgate/transfer.py, solgate/utils/io.py, solgate/utils/s3.py
This should help with transfers of large files as well as provide a way to better monitor sync progress.
=> Fix file counting and up the read timeout on S3

manifests/overlays/prod/floorist/cronwf.yaml, manifests/overlays/prod/floorist/floorist.enc.yaml
https://github.com/aicoe-aiops/sync-pipelines/pull/125
=> Reschedule floorist to run only once a day for now

manifests/overlays/prod/floorist/floorist.enc.yaml
This file was previously edited without using the sops tool, so the sops
metadata was in a broken state. This change resopsifys the file to get
it working again.
…
… Explain your changes.
=> Fix sops metadata for floorist file

tests/cli_test.py, tests/transfer_test.py, tests/utils/io_test.py
I forgot to update the test suite when working on #119
This should fix it, sorry! :disappointed:
=> fix(test): Update test suite for #119

manifests/overlays/prod/usir/secret.enc.yaml
=> feat: Update USIR creds

.thoth.yaml
=> Add accorvin as a maintainer

manifests/overlays/prod/kustomization.yaml, manifests/overlays/prod/rhods-usage-metrics-dev/cronwf.yaml, manifests/overlays/prod/rhods-usage-metrics-dev/kustomization.yaml, manifests/overlays/prod/rhods-usage-metrics-dev/secret-generator.yaml, manifests/overlays/prod/rhods-usage-metrics-dev/secret.enc.yaml
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
=> Add Solgate Pipeline for dev RHODS metrics
