- README.md
#7 
A documentation change - updates the Readme to better fit `solgate` instead of `dh-argo-workflows`.
> Update readme to fit Solgate

- Pipfile
- Pipfile.lock
Should suppress PRs like #12 and #8 
We had a `allow_prereleases = true` flag set in our `Pipfile` in order to install and maintain `black` dev package (which has no stable release what so ever). However this setting causes sesheta to look up other package's prereleases as well, and advertises them in a PR (like #12 or #8). That may cause troubles, because we may not want prereleased dependencies in the package environment. This PR locks `black` to its latest available version and removes the `allow_prerelease` flag from the config.
> Set pipenv to not install prereleases

- .aicoe-ci.yaml
aicoe-ci config file, to custom ci feature requirement:truck: aicoe-ci config file, to custom ci feature requirement
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Related-To: https://github.com/AICoE/aicoe-ci/issues/41
- Added aicoe-ci configuration file, for allowing sync-pipeline maintainer to pick and choose aicoe-ci feature for sync-pipeline.
- Disabled pytest in aicoe-ci configuration file.
This feature would take effect once this PR is merged.
> aicoe-ci config file, to custom ci feature requirement

- solgate/cli.py
- solgate/lookup.py
- solgate/utils/__init__.py
- solgate/utils/io.py
- solgate/utils/s3.py
- tests/fixtures/sample_config.ini
- tests/utils/io_test.py
#1 
Instead of one single parser, split it into 2 more distinct parsers:
1. For all the S3 related sections ( `source_*` and `destination_*`s )
2. For the general section `solgate`, that is now utilized for `timedelta` (will be used by the notification service as well)
Adding test coverage for all the config parsings.
> Make use of the general config section and split the parsers + test coverage

- .aicoe-ci.yaml
Related to #22 
Resolves: #4 
Use AICoE-CI to build and publish the Solgate image.
> Build and publish using AICoE-CI

- Pipfile
- Pipfile.lock
`https://github.com/aio-libs/aiobotocore/issues/755`
With recent update of s3fs, they switched over to aiobotocore instead of botocore. This new depencency introduces a regressions, since it doesn't return full s3 responses anymore - this breaks testing via [moto](https://github.com/spulec/moto). A downgrade to 0.4.* is a necessary workaround to get the tests green again. Until resolved upstream...
> Downgrade s3fs to 0.4

- manifests/base/wftmpl.yaml
- solgate/utils/io.py
…
Kubernetes mounts secrets as whole folders, let's adjust our expected mount/config file location to this.
> Change default config location to a mountable dir for better Kubernetes support

- manifests/base/image-transformer-configuration.yaml
- manifests/base/kustomization.yaml
...
Switch the manifests over to use the Quay.ion image of solgate built by AICoE-CI: https://quay.io/repository/thoth-station/solgate
> Map solgate images to pull from quay.io

- solgate/utils/io.py
- solgate/utils/s3.py
- tests/fixtures/sample_config.ini
- tests/fixtures/single_destination.ini
- tests/transfer_test.py
- tests/utils/io_test.py
- tests/utils/s3_test.py
…
Allow for `config.ini` to contain section named like `source` and `destination`. Previously an additional name in there was required `source_SOMETHING` and `destination_SOMETHING`. It was really just a pain... This allows for cleaner configs when a single source and a single destination is present...
> Allow section names without underscore

- setup.py
sesheta was unable to help in pypi release due to:
`HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/`
https://pypi.org/help/#description-content-type
set description content type in setup.py
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> set description content type in setup.py

- solgate/cli.py
- solgate/transfer.py
- tests/cli_test.py
- tests/transfer_test.py
…
During testing of #39 I've discovered a bug in the transfer logic - the code was looking up the Object's `key` in the listing file, instead of `relpath`. This resulted in the `base_path` not being subtracted from the file key, therefore the transfer was not able to locate the source file properly.
When listing file is used for transfer, the `relpath` attribute of each file is present there. When using direct key in cli, user is expected to use the `relpath` instead of full key.
```sh
$ cat config.ini
[source]
base_path = BUCKET/a/b
...
solgate send BUCKET/a/b/file.txt
solgate send file.txt
```
> Fix transfer logic - look for 'relpath' key instead of 'key'

- README.md
- solgate/cli.py
- solgate/report.py
- tests/cli_test.py
- tests/report_test.py
- tests/transfer_test.py
…
Simplify the `solgate report` command by allowing to specify the sender, recipient and SMTP server via CLI and env var. That allows use of the reporter without a config file all together, making solgate reporter usable in non-solgate scenarios that wants to use Argo email reporting.
> Allow reports without config file

- manifests/overlays/prod/mms/secret.enc.yaml
n/a
Remove custom time constrain for MMS on the timedelta window for modified data, so we overlap the sync - job scheduled every 6 hours, looking for data modified in last 24 hours.
> fix: Make MMS pipeline overlap the time constrain

- solgate/transfer.py
Flush the remote FS after each file copy. It seems that in some cases the new file is not written all the way through to the remote FS. Reason unknown. Hopefully flushing after each file solves that...
> fix: Attept to flush remote FS

- manifests/base/wftmpl.yaml
SSIA
separate optional param makes the pipeline fail if left empty
> fix: Optional param in wftmpl

- Pipfile
- Pipfile.lock
- solgate/cli.py
- solgate/lookup.py
- solgate/transfer.py
- solgate/utils/s3.py
- tests/cli_test.py
- tests/conftest.py
- tests/lookup_test.py
- tests/transfer_test.py
- tests/utils/s3_test.py
> Switch to boto3, add `--silent`, `--dry-run` and retry loginc

- setup.py
SSIA, broken build because of missing `boto3` and `backoff`. Hopefully this will fix it
> fix: List all deps in setup.py

- manifests/backfill.yaml
- manifests/base/image-transformer-configuration.yaml
- manifests/base/wftmpl.yaml
Introduce a simple splitter on amount of files to sync (defaults to 5000 per pod) to parallelize long running syncs - it spawns a new pod for every X files to be synced.
Also adds an auxilary file listing step - to get quick stats on how many files each pod syncs and how many files we're syncing in total. Just a plain and redundant kinda-logger step.
> feat(manifets): Split file list to partials to parallelize sync

- manifests/overlays/prod/cost-management/cronwf.yaml
n/a
Koku is hitting pod deadline timeouts on sync. Let's try splitting much sooner into multiple pods.
Last sync was about 1800 files in total, let's try 150 files per worker.
> feat: Set Koku pipeline to split on 150 files

- manifests/overlays/prod/floorist/floorist.enc.yaml
https://github.com/aicoe-aiops/sync-pipelines/pull/123
https://issues.redhat.com/browse/APPSRE-4003
We're dumping data every 24 hour, but we would like to have the synchronization (not failing) in every 12. This is a failsafe setting that copies a bit more data and prevents the system from failing if there are no new dump files.
@Victoremepunto @tumido @accorvin
> Adjust floorist timedelta to 24 hours for failsafe

- manifests/overlays/prod/tower-analytics-prod/secret.enc.yaml
- manifests/overlays/prod/tower-analytics-stage/secret.enc.yaml
Change `tower-*` pipelines config to report to idh alerts instead of tumido.
> chore: Report Tower analytics to datahub not to tumido

- manifests/base/wftmpl.yaml
n/a
Sometimes steps fail due to cluster instability, e.g. pod was terminated and evicted. Lets retry the step in such cases.
This recently happened at http://argo-server-aiops-prod-argo.apps.ocp4.prod.psi.redhat.com/workflows/aiops-prod-argo/solgate-floorist-1641816000
> fix: Retry on failures

- solgate/transfer.py
- solgate/utils/s3.py
- tests/conftest.py
- tests/transfer_test.py
- tests/utils/s3_test.py
The s3fs copy function was attemting to use a multipart upload to copy,
which was failing. Switching to boto3 resolves this issue.
> Update copy function to use boto3

- manifests/overlays/prod/rhods-usage-metrics-dev/secret.enc.yaml
- solgate/cli.py
- solgate/lookup.py
- solgate/utils/__init__.py
- solgate/utils/io.py
- tests/cli_test.py
- tests/lookup_test.py
- tests/utils/io_test.py
Implements the ability to disable, from config, a workflow's failures/alerts caused by a bucket simply not having new files to sync within its given TIMEDELTA
Implements the ability to disable the NoFilesToSyncError on `solgate list`, which causes the entire pipeline to fail if encountered
The rest of the Argo Workflow happens to already handle this well (will skip the sync step if no json files to act on) and this allows per-workflow configuration to reduce alert fatigue stemming from low-traffic buckets
Also adds this new configuration item to the wf def for the dh-rhods-usage-metrics-dev sync pipeline, whose constant alert emails inspired this PR :)
> Add configurable ability for workflows to skip (instead of alert) when no new files available to sync.
